name: deploy production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.72.0'

    - name: Build
      run: hugo --minify -e production

    - name: Deploy
      run: scp -r public ${{ secrets.SCP_USERNAME }}@kaes3kuch3n.de:/home/test/public
