name: deploy production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.72.0'

    - name: Build
      run: hugo --minify -e production

    - name: Deploy
      uses: appleboy/scp-action@v0.1.1
      with:
        host: kaes3kuch3n.de
        username: ${{ secrets.SCP_USERNAME }}
        password: ${{ secrets.SCP_PASSWORD }}
        target: /home/test
        source: public/
        rm: true
